### ISSUE TITLE
[Django] TIL Blog project Tracker

### ISSUE THREAD

**Issue by 4923** [4923/GwangjuAI2#4]
- [Project dir](https://github.com/4923/GwangjuAI2/tree/master/02_Rotation/WebApplication/Project/personalProject)
- 한 comment에 하나의 App의 내용만 담을 것
- 🔴 할 일 목록은 Projects에서 관리.
- 🔴 issue 에는 전반적인 개발 진행상황 및 아카이빙이 필요한 내용 기록

**Comment by 4923** [comment]
## articleapp/

**CRUD**
- [ ] C  / 게시글 작성 기능 구현
- [ ] R / 게시글 열람 페이지 구현
- [ ] U / 게시글 수정 기능 구현
- [ ] D / 게시글 삭제 기능 구현

**Comment by 4923** [comment]
https://github.com/4923/GwangjuAI2/projects/2#card-66329218
